site_name: My Docs
site_url: https://silmarill07.github.io/docs/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs
    - content.code.copy
  nav:
    Linux:
      - Alias: alias.md
    Windows:
      - Настройка MS Edge: Настройка-MS-Edge.md
    Tags: tags.md 

  palette: 
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  copyright: '2025, My Docs'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets


plugins:
  - search
  - tags